# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20170321_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='epost',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='tilbakemelding',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='glad',
            new_name='happy',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='navn',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='linje',
            new_name='programme',
        ),
    ]
